/* Personal seed: source-checked Sep 5, 2026; no credentials or student ID. */
window.STRIDE_SEED = {
  version: 1,
  settings: { name: 'Harris', timezone: 'America/Los_Angeles', dayStart: '08:00', dayEnd: '22:30', block: 50, energy: 'balanced', dailyFocus: 300, buffer: 15, theme: 'light' },
  sourceCheckedAt: '2026-09-05T21:45:00-07:00',
  term: { start: '2026-08-26', end: '2026-12-04', name: 'Fall 2026', holidays: ['2026-09-07','2026-11-11','2026-11-25','2026-11-26','2026-11-27'] },
  courses: [
    {id:'math53', name:'Math 53', title:'Multivariable calculus', color:'purple', icon:'math', instructor:'James Sethian', units:4, note:'Read the assigned sections before each Tuesday and Thursday lecture. Homework and quiz specifics must come from your current section.', links:[{label:'Homework & readings',url:'https://math.berkeley.edu/~sethian/math53_2026/homeworks.html'},{label:'bCourses',url:'https://bcourses.berkeley.edu/courses/1557957'},{label:'Gradescope',url:'https://www.gradescope.com/'}]},
    {id:'cs61b',name:'CS 61B',title:'Data structures',color:'coral',icon:'code',instructor:'Course staff',units:4,note:'No-attendance track. Your M/W/F 2-3 PM learning blocks are flexible, not extra attendance requirements. Assignments still apply.',links:[{label:'Course & readings',url:'https://fa26.datastructur.es/'},{label:'Project 0',url:'https://fa26.datastructur.es/projects/proj0/'},{label:'Ed',url:'https://edstem.org/us/courses/102248/discussion/'}]},
    {id:'cs70',name:'CS 70',title:'Discrete math & probability',color:'blue',icon:'nodes',instructor:'Sam Poder - discussion',units:4,note:'Wednesday discussion and Friday quiz section are separate commitments. Friday quiz content is not necessarily the newest lecture.',links:[{label:'Course calendar',url:'https://www.eecs70.org/'},{label:'Homework 1',url:'https://www.eecs70.org/assets/pdf/hw01.pdf'},{label:'Ed',url:'https://edstem.org/us/courses/102319/discussion/'}]},
    {id:'ee66',name:'EE 66',title:'Signals, dynamics & information',color:'green',icon:'wave',instructor:'Jonathan - Friday lab',units:4,note:'Lecture is Monday/Wednesday, not Friday. Your chosen lab slot is Friday 3-6 PM. Individual lab weeks and the discussion slot need confirmation.',links:[{label:'bCourses',url:'https://bcourses.berkeley.edu/courses/1558788'},{label:'Ed',url:'https://edstem.org/us/courses/104109/discussion/'},{label:'Lab announcement',url:'https://edstem.org/us/courses/104109/discussion/8215982'}]}
  ],
  events: [
    {id:'math-lec',course:'math53',title:'Sethian lecture',kind:'lecture',days:[2,4],start:'08:00',end:'09:30',from:'2026-08-26',until:'2026-12-04',mode:'fixed',location:'Location not recorded',confidence:'user',source:'Your CalCentral screenshot',notes:'Prepare the assigned reading before this meeting.'},
    {id:'math-disc',course:'math53',title:'Discussion',kind:'discussion',days:[1,3,5],start:'11:00',end:'12:00',from:'2026-08-26',until:'2026-12-04',mode:'fixed',location:'Confirm room in CalCentral',confidence:'user',source:'Your CalCentral screenshot',notes:'Quizzes may take place in section. Exact quiz dates are not verified; do not assume every Friday is a quiz.'},
    {id:'61b-learn',course:'cs61b',title:'Lecture material / self-study',kind:'study',days:[1,3,5],start:'14:00',end:'15:00',from:'2026-08-26',until:'2026-12-04',mode:'flexible',location:'Anywhere / Wheeler 150 for live lecture',confidence:'user',source:'Your chosen learning rule; official 61B meeting time',url:'https://fa26.datastructur.es/',notes:'Move this block freely. Skipping live lecture does not complete the material.'},
    {id:'70-lec',course:'cs70',title:'Lecture',kind:'lecture',days:[2,4],start:'15:30',end:'17:00',from:'2026-08-26',until:'2026-12-04',mode:'fixed',exceptions:['2026-10-15'],location:'Li Ka Shing 245',confidence:'verified',source:'CS70 Fall 2026 course calendar, checked Sep 5',url:'https://www.eecs70.org/',notes:'Default: attend. Change to flexible when intentionally using the recording, and keep a catch-up task.'},
    {id:'70-disc',course:'cs70',title:'Discussion with Sam Poder',kind:'discussion',days:[3],start:'09:00',end:'10:00',from:'2026-09-02',until:'2026-12-04',mode:'fixed',location:'Cory 237',confidence:'user',source:'Your section signup and attendance',notes:'Keep this separate from the Friday quiz.'},
    {id:'66-lec',course:'ee66',title:'Lecture',kind:'lecture',days:[1,3],start:'18:30',end:'20:00',from:'2026-08-26',until:'2026-12-04',mode:'fixed',location:'Pimentel 1 - verify room',confidence:'user',source:'CalCentral screenshot (MW 6:30-7:59 PM)',notes:'No Friday lecture. Allow travel time if an exam starts at 8 PM.'},
    {id:'66-lab',course:'ee66',title:'Lab with Jonathan',kind:'lab',days:[5],start:'15:00',end:'18:00',from:'2026-09-07',until:'2026-12-04',mode:'reserved',location:'Confirm lab room in Ed',confidence:'user',source:'Your Friday 3-6 PM selection',url:'https://edstem.org/us/courses/104109/discussion/',notes:'Reserved slot, NOT confirmation that a lab meets every Friday. Staff previously announced six labs. Enter the actual lab dates when verified.'}
  ],
  exams: [
    {id:'61b-m1',course:'cs61b',title:'Mini-midterm 1',date:'2026-09-23',start:'20:00',end:'21:20',kind:'exam',mode:'fixed',confidence:'verified',source:'Official CS61B calendar, checked Sep 5',url:'https://fa26.datastructur.es/',location:'Room to be announced'},
    {id:'math-m1',course:'math53',title:'Midterm 1',date:'2026-10-01',start:'08:00',end:'09:30',kind:'exam',mode:'reserved',confidence:'review',replace:'math-lec',source:'Previously discussed date; current-term source not reverified',location:'Verify with Sethian'},
    {id:'70-m1',course:'cs70',title:'Midterm',date:'2026-10-16',start:'19:00',end:'21:00',kind:'exam',mode:'fixed',confidence:'verified',source:'Official CS70 calendar, checked Sep 5',url:'https://www.eecs70.org/',location:'Room to be announced'},
    {id:'61b-m2',course:'cs61b',title:'Midterm 2',date:'2026-11-04',start:'20:00',end:'22:00',kind:'exam',mode:'fixed',confidence:'verified',source:'Official CS61B calendar, checked Sep 5',url:'https://fa26.datastructur.es/',location:'Room to be announced'},
    {id:'math-m2',course:'math53',title:'Midterm 2',date:'2026-11-05',start:'08:00',end:'09:30',kind:'exam',mode:'reserved',confidence:'review',replace:'math-lec',source:'Previously discussed date; current-term source not reverified',location:'Verify with Sethian'},
    {id:'math-final',course:'math53',title:'Final exam',date:'2026-12-16',start:'15:00',end:'18:00',kind:'exam',mode:'fixed',confidence:'user',source:'Your CalCentral screenshot; future times can change',location:'Room to be announced'},
    {id:'61b-final',course:'cs61b',title:'Final exam',date:'2026-12-17',start:'15:00',end:'18:00',kind:'exam',mode:'reserved',confidence:'review',source:'CalCentral screenshot; course website still says date/time TBD',location:'Reconcile final time with staff'},
    {id:'66-final',course:'ee66',title:'Final exam',date:'2026-12-18',start:'15:00',end:'18:00',kind:'exam',mode:'fixed',confidence:'user',source:'Your CalCentral screenshot; future times can change',location:'Room to be announced'},
    {id:'70-final',course:'cs70',title:'Final exam',date:'2026-12-18',start:'19:00',end:'22:00',kind:'exam',mode:'fixed',confidence:'verified',source:'Official CS70 calendar, checked Sep 5',url:'https://www.eecs70.org/',location:'Room to be announced'}
  ],
  quizzes: [
    ['2026-09-04','Quiz 0: Direct proofs'],['2026-09-11','Quiz 1: Propositional logic & proof techniques'],['2026-09-18','Quiz 2: Induction & modular arithmetic'],['2026-09-25','Quiz 3: CRT & RSA'],['2026-10-02','Quiz 4: Polynomials & secret sharing'],['2026-10-09','Quiz 5: Graphs & induction'],['2026-10-23','Quiz 6: Countability & computability'],['2026-10-30','Quiz 7: Counting & probability'],['2026-11-06','Quiz 8: Combinatorial proofs & Bayes'],['2026-11-13','Quiz 9: Independence & random variables'],['2026-11-20','Quiz 10: Expectations & joint distributions'],['2026-12-04','Quiz 11: Variance & continuous probability']
  ],
  tasks: [
    {id:'m-hw2',course:'math53',title:'Homework 2',kind:'homework',availability:'open',status:'progress',due:'2026-09-08T09:00',dueConfidence:'review',remaining:300,energy:'deep',next:'Open the next unfinished section. Scan each completed whiteboard panel before erasing.',notes:'Deadline carried over from the earlier audit, not reverified today. Check Gradescope. Remaining time is a starting estimate, not a prediction; update it to reflect what is left.',source:'Earlier course audit; you reported starting on Sep 3',url:'https://bcourses.berkeley.edu/courses/1557957',checked:'2026-09-05',steps:['Finish section 10.3','Finish sections 10.4-10.5','Finish sections 12.1-12.2','Finish section 12.3','Finish sections 12.4-12.5','Check images and submit on Gradescope'],checkedSteps:[]},
    {id:'b-proj0',course:'cs61b',title:'Project 0: Particle Simulator',kind:'project',availability:'open',status:'todo',due:'2026-09-08T23:59',dueConfidence:'verified',remaining:180,energy:'deep',next:'Open the specification, run the skeleton, and identify the next unfinished milestone.',notes:'No recent completion was confirmed. Set your actual remaining time and status. Do not infer a missing submission just from a missing email.',source:'CS61B course calendar checked Sep 5',url:'https://fa26.datastructur.es/',checked:'2026-09-05',steps:['Read specification and run skeleton','Complete implementation','Run tests and review requirements','Submit and verify receipt'],checkedSteps:[]},
    {id:'b-hw3',course:'cs61b',title:'Homework 3: IntLists',kind:'homework',availability:'open',status:'todo',due:'2026-09-08T23:59',dueConfidence:'review',remaining:90,energy:'balanced',next:'Pull the skeleton and begin the debugger task.',notes:'Release confirmed in Sep 4 Ed email. Sep 8 due date appears on the calendar; the exact cutoff should be checked on Gradescope.',source:'Ed release email and CS61B official calendar checked Sep 5',url:'https://fa26.datastructur.es/homeworks/hw03/',checked:'2026-09-05',steps:['Read the assignment','Debugger and IntList tasks','Test and submit'],checkedSteps:[]},
    {id:'b-survey',course:'cs61b',title:'Week 2 survey',kind:'admin',availability:'open',status:'todo',due:'2026-09-08T23:59',dueConfidence:'verified',remaining:5,energy:'light',next:'Open the course homepage and follow the Week 2 Survey link.',notes:'Published 24-hour grace period. Separate from the pre-semester survey you already finished. Mark done if already completed.',source:'Official CS61B Week 2 announcement checked Sep 5',url:'https://fa26.datastructur.es/',checked:'2026-09-05',steps:[],checkedSteps:[]},
    {id:'70-hw1',course:'cs70',title:'Homework 1',kind:'homework',availability:'open',status:'todo',due:'2026-09-09T16:00',dueConfidence:'verified',remaining:180,energy:'deep',next:'Start the truth-table problem; mark proof questions that need office hours.',notes:'The official PDF is available now. Grace ends Sep 9 at 6 PM. Include a truthful collaboration statement.',source:'Official CS70 HW01 PDF checked Sep 5',url:'https://www.eecs70.org/assets/pdf/hw01.pdf',checked:'2026-09-05',steps:['Truth tables and propositions','Quantifiers and proofs','Remaining proof problems','Good-faith stretch attempt','Sundry, check and submit'],checkedSteps:[]},
    {id:'70-quiz1',course:'cs70',title:'Prepare for Quiz 1',kind:'review',availability:'open',status:'todo',due:'2026-09-11T09:00',dueConfidence:'verified',remaining:45,energy:'balanced',next:'Try representative propositional-logic and proof-technique questions without notes.',notes:'Preparation target is the start of your 9 AM quiz section, not an online assignment cutoff.',source:'Official CS70 quiz calendar; your registered 9 AM section',url:'https://www.eecs70.org/',checked:'2026-09-05',steps:['Practice without notes','Review mistakes'],checkedSteps:[]},
    {id:'b-next-project',course:'cs61b',title:'Project 1: LinkedListDeque',kind:'project',availability:'waiting',status:'todo',release:'2026-09-09T09:00',due:'2026-09-15T23:59',dueConfidence:'review',remaining:180,energy:'deep',next:'Wait for the release announcement, then review the specification.',notes:'Upcoming on the calendar. Sep 9 is the listed calendar day, not a guaranteed 9 AM release. A date passing does not prove publication.',source:'Future CS61B calendar row checked Sep 5',url:'https://fa26.datastructur.es/',checked:'2026-09-05',steps:[],checkedSteps:[]},
    {id:'66-next',course:'ee66',title:'Next homework / mini-vitamin',kind:'homework',availability:'unknown',status:'todo',due:'',dueConfidence:'review',remaining:60,energy:'balanced',next:'Check Ed and Gradescope for the next published item.',notes:'This is a watch item, not a claim that no assignment exists. Replace it with the actual assignment when verified.',source:'No current release verified in this build',url:'https://edstem.org/us/courses/104109/discussion/',checked:'2026-09-05',steps:[],checkedSteps:[]},
    {id:'66-hw1',course:'ee66',title:'Homework 1',kind:'homework',availability:'open',status:'submitted',due:'2026-09-04T23:59',dueConfidence:'verified',remaining:0,energy:'deep',completedAt:'2026-09-02T16:38',source:'Gradescope submission receipt checked Sep 5',notes:'Submission confirmed, not a claim about the grade.',steps:[],checkedSteps:[]},
    {id:'70-hw0',course:'cs70',title:'Homework 0',kind:'homework',availability:'open',status:'submitted',due:'2026-09-02T16:00',dueConfidence:'verified',remaining:0,completedAt:'2026-09-01T18:08',source:'Gradescope submission receipt checked Sep 5',notes:'Submitted. Feedback forms, when required, are separate tasks.',steps:[],checkedSteps:[]},
    {id:'70-quiz0',course:'cs70',title:'Quiz 0',kind:'quiz',availability:'open',status:'submitted',due:'2026-09-04T10:00',dueConfidence:'verified',remaining:0,completedAt:'2026-09-04T09:37',source:'Gradescope 9 AM quiz receipt checked Sep 5',notes:'Receipt confirms submission, not score.',steps:[],checkedSteps:[]},
    {id:'m-hw1',course:'math53',title:'Homework 1',kind:'homework',availability:'open',status:'submitted',due:'2026-09-01T08:00',dueConfidence:'user',remaining:0,completedAt:'2026-08-30T19:29',source:'Earlier conversation submission check',steps:[],checkedSteps:[]},
    {id:'b-hw2',course:'cs61b',title:'Homework 2: Java intro',kind:'homework',availability:'open',status:'submitted',due:'2026-09-01T23:59',dueConfidence:'verified',remaining:0,completedAt:'2026-09-01T12:00',source:'Earlier submission confirmation in conversation',steps:[],checkedSteps:[]},
    {id:'b-hw1',course:'cs61b',title:'Homework 1: Setup',kind:'homework',availability:'open',status:'submitted',due:'2026-08-28T23:59',dueConfidence:'user',remaining:0,completedAt:'2026-08-27T12:00',source:'Your completed-work history',steps:[],checkedSteps:[]},
    {id:'66-hw0',course:'ee66',title:'Homework 0',kind:'homework',availability:'open',status:'submitted',due:'2026-08-28T23:59',dueConfidence:'user',remaining:0,completedAt:'2026-08-27T21:00',source:'Your completion report',steps:[],checkedSteps:[]},
    {id:'b-survey0',course:'cs61b',title:'Pre-semester survey',kind:'admin',availability:'open',status:'done',due:'2026-08-28T23:59',dueConfidence:'user',remaining:0,completedAt:'2026-08-27T22:00',source:'Your completion report',steps:[],checkedSteps:[]},
    {id:'66-lab-signup',course:'ee66',title:'Friday lab signup',kind:'admin',availability:'open',status:'done',due:'',dueConfidence:'user',remaining:0,completedAt:'2026-09-04T13:16',source:'You confirmed choosing Friday 3-6 PM with Jonathan',steps:[],checkedSteps:[]}
  ],
  reviews: [
    {id:'discussion',course:'ee66',title:'Place your EE66 discussion',detail:'You attended Tuesday and Thursday, but the exact recurring days/time were never reliably established. Add the actual slot before treating any timetable as complete.',action:'discussion',url:'https://edstem.org/us/courses/104109/discussion/',resolved:false},
    {id:'labdates',course:'ee66',title:'Confirm which Fridays have a lab',detail:'Your Friday 3-6 PM slot is chosen. The individual lab dates and room are not verified. Reserved blocks protect your time without inventing weekly attendance.',action:'labdates',url:'https://edstem.org/us/courses/104109/discussion/8215982',resolved:false},
    {id:'vitamin',course:'ee66',title:'Reconcile the mini-vitamin reminder',detail:'An Ed email says Mini Vitamin 1 was due Sep 3. An earlier audit marked Lecture 1A Mini-Vitamin submitted. Verify whether these refer to the same item; neither assume overdue nor ignore it.',action:'review',url:'https://edstem.org/us/courses/104109/discussion/',resolved:false},
    {id:'feedback',course:'cs70',title:'Check HW0 feedback requirements',detail:'Staff emailed HW0 Solutions Released & HW Feedback on Sep 3. The full post and any feedback deadline still need checking.',action:'review',url:'https://edstem.org/us/courses/102319/discussion/',resolved:false},
    {id:'66exams',course:'ee66',title:'Add EE66 midterms',detail:'The exact midterm dates have not been verified. The app cannot certify an exam-conflict-free semester until these are added.',action:'exam',url:'https://bcourses.berkeley.edu/courses/1558788',resolved:false}
  ],
  sessions: [],
  notes: [],
  eventOverrides: {},
  readingPlans: {},
  activity: [{at:'2026-09-05T21:45:00-07:00',text:'Planner initialized from your conversation, screenshots, current public course pages, and Berkeley submission/release emails.'}]
};
